//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMJ.Authenticator.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfrastructureString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfrastructureString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMJ.Authenticator.Infrastructure.Properties.InfrastructureString", typeof(InfrastructureString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is either ambiguous even factory or no one to use. There must be just one registered..
        /// </summary>
        internal static string AmbiguousOrNoOneEventFactory {
            get {
                return ResourceManager.GetString("AmbiguousOrNoOneEventFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is either ambiguous even handler or no one to use. There must be just one registered..
        /// </summary>
        internal static string AmbiguousOrNoOneEventHandlerStrategy {
            get {
                return ResourceManager.GetString("AmbiguousOrNoOneEventHandlerStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNameOrPasswordNotValid.
        /// </summary>
        internal static string ErrorAuthenticateMemberCode {
            get {
                return ResourceManager.GetString("ErrorAuthenticateMemberCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password wich were sent are not correct, either the user doesn&apos;t exist or password isn&apos;t correct..
        /// </summary>
        internal static string ErrorAuthenticateMemberDetail {
            get {
                return ResourceManager.GetString("ErrorAuthenticateMemberDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 409.
        /// </summary>
        internal static string ErrorAuthenticateMemberHttpStatusCode {
            get {
                return ResourceManager.GetString("ErrorAuthenticateMemberHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name or password aren&apos;t valid..
        /// </summary>
        internal static string ErrorAuthenticateMemberTitle {
            get {
                return ResourceManager.GetString("ErrorAuthenticateMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.Argument..
        /// </summary>
        internal static string ErrorCodeArgumentPrefix {
            get {
                return ResourceManager.GetString("ErrorCodeArgumentPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.InvalidOperation..
        /// </summary>
        internal static string ErrorCodeInvalidOperationPrefix {
            get {
                return ResourceManager.GetString("ErrorCodeInvalidOperationPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserWasNotCreated.
        /// </summary>
        internal static string ErrorCreateUserCode {
            get {
                return ResourceManager.GetString("ErrorCreateUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because of internal error the user wasn&apos;t created, please contact with user administrator..
        /// </summary>
        internal static string ErrorCreateUserDetail {
            get {
                return ResourceManager.GetString("ErrorCreateUserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 409.
        /// </summary>
        internal static string ErrorCreateUserHttpStatusCode {
            get {
                return ResourceManager.GetString("ErrorCreateUserHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not created..
        /// </summary>
        internal static string ErrorCreateUserTitle {
            get {
                return ResourceManager.GetString("ErrorCreateUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserWasNotDeleted.
        /// </summary>
        internal static string ErrorDeleteUserCode {
            get {
                return ResourceManager.GetString("ErrorDeleteUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because of internal error the user wasn&apos;t deleted, please contact with user administrator..
        /// </summary>
        internal static string ErrorDeleteUserDetail {
            get {
                return ResourceManager.GetString("ErrorDeleteUserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 409.
        /// </summary>
        internal static string ErrorDeleteUserHttpStatusCode {
            get {
                return ResourceManager.GetString("ErrorDeleteUserHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not deleted..
        /// </summary>
        internal static string ErrorDeleteUserTitle {
            get {
                return ResourceManager.GetString("ErrorDeleteUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItDoesNotExistAnyUser.
        /// </summary>
        internal static string ErrorGetAllUserCode {
            get {
                return ResourceManager.GetString("ErrorGetAllUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no saved users to get..
        /// </summary>
        internal static string ErrorGetAllUserDetail {
            get {
                return ResourceManager.GetString("ErrorGetAllUserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404.
        /// </summary>
        internal static string ErrorGetAllUserHttpStatusCode {
            get {
                return ResourceManager.GetString("ErrorGetAllUserHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It doesn&apos;t exist any user..
        /// </summary>
        internal static string ErrorGetAllUserTitle {
            get {
                return ResourceManager.GetString("ErrorGetAllUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserWasNotUpdated.
        /// </summary>
        internal static string ErrorUpdateUserCode {
            get {
                return ResourceManager.GetString("ErrorUpdateUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because of internal error the user wasn&apos;t updated, please contact with user administrator..
        /// </summary>
        internal static string ErrorUpdateUserDetail {
            get {
                return ResourceManager.GetString("ErrorUpdateUserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 409.
        /// </summary>
        internal static string ErrorUpdateUserHttpStatusCode {
            get {
                return ResourceManager.GetString("ErrorUpdateUserHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not updated..
        /// </summary>
        internal static string ErrorUpdateUserTitle {
            get {
                return ResourceManager.GetString("ErrorUpdateUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event was not created due to invalid inputs.
        /// </summary>
        internal static string EventCreationFailure {
            get {
                return ResourceManager.GetString("EventCreationFailure", resourceCulture);
            }
        }
    }
}
